### ISSUE TITLE
[Bug] TypeError in SDK python testcase

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/certification-tool#123]
### Describe the bug

TC-CGEN-2.4 and TC-IDM-1.2 are failed with the `TypeError: 'NoneType' object is not subscriptable`. The docker used for Execution of the SDK python testcases needs tobe updated to hadle these type of issue. 

> PYTHON_TEST | 2023-12-14 10:55:43.537792 | Traceback (most recent call last):
PYTHON_TEST | 2023-12-14 10:55:43.539808 |   File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 783, in exec_one_test
PYTHON_TEST | 2023-12-14 10:55:43.542214 |     test_method()
PYTHON_TEST | 2023-12-14 10:55:43.546073 |   File "/root/python_testing/matter_testing_support.py", line 1317, in async_runner
PYTHON_TEST | 2023-12-14 10:55:43.548656 |     return asyncio.run(runner_with_timeout)
PYTHON_TEST | 2023-12-14 10:55:43.551720 |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
PYTHON_TEST | 2023-12-14 10:55:43.553927 |     return loop.run_until_complete(main)
PYTHON_TEST | 2023-12-14 10:55:43.555570 |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
PYTHON_TEST | 2023-12-14 10:55:43.557021 |     return future.result()
PYTHON_TEST | 2023-12-14 10:55:43.558548 |   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
PYTHON_TEST | 2023-12-14 10:55:43.560117 |     return fut.result()
PYTHON_TEST | 2023-12-14 10:55:43.561900 |   File "/root/python_testing/TC_IDM_1_2.py", line 187, in test_TC_IDM_1_2
PYTHON_TEST | 2023-12-14 10:55:43.563919 |     discriminator = self.matter_test_config.discriminators[0] + 1
PYTHON_TEST | 2023-12-14 10:55:43.566554 | TypeError: 'NoneType' object is not subscriptable
PYTHON_TEST | 2023-12-14 10:55:43.569813 | [MatterTest] 12-14 10:55:42.927 INFO [Test] test_TC_IDM_1_2 ERROR

### Log files

[cgen-2-4.log](https://github.com/project-chip/certification-tool/files/13673998/cgen-2-4.log)
[idm-1-2.log](https://github.com/project-chip/certification-tool/files/13674050/idm-1-2.log)

### Additional Information

Note : this testcases is failed only in the UI but passed in the connectedhomeip/chip-cert-bins docker.

**Comment by rquidute** [comment]
Hi @Saravana-kr22 Could you please provide the command used  in `connectedhomeip/chip-cert-bins` docker ?

**Comment by Saravana-kr22** [comment]
Command used in connectedhomeip/chip-cert-bins docker :

TC-CGEN-2.4 - python3 TC_CGEN_2_4.py --commissioning-method on-network --discriminator 3840 --passcode 20202021  --paa-trust-store-path /credentials/development/paa-root-certs/ --storage-path admin_storage.json 
TC-IDM-1.2 -   python3 TC_IDM_1_2.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --PICS ci-pics-values --paa-trust-store-path /credentials/development/paa-root-certs/

**Comment by rquidute** [comment]
PRs that fix the issues:
TC_CGEN-2.4: https://github.com/project-chip/connectedhomeip/pull/31044
TC_IDM-1.2: https://github.com/project-chip/connectedhomeip/pull/31046

**Comment by Saravana-kr22** [comment]
This issue is resolved in the latsest TH `Version: 2.10-beta2+spring2024`
